-- グループ予算テーブルの作成
create table if not exists public.group_budgets (
    id bigint generated by default as identity primary key,
    group_id bigint not null references public.groups(id) on delete cascade,
    category text not null,
    amount integer not null check (amount > 0),
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
    -- グループとカテゴリーの組み合わせでユニーク制約
    unique(group_id, category)
);

-- RLSポリシーの設定
alter table public.group_budgets enable row level security;

-- グループメンバーのみが予算を閲覧・編集可能
create policy "グループメンバーのみ予算の閲覧が可能" on public.group_budgets
    for select
    using (
        exists (
            select 1 from public.group_members
            where group_members.group_id = group_budgets.group_id
            and group_members.user_id = auth.uid()
        )
    );

create policy "グループ管理者のみ予算の作成が可能" on public.group_budgets
    for insert
    with check (
        exists (
            select 1 from public.group_members
            where group_members.group_id = group_budgets.group_id
            and group_members.user_id = auth.uid()
            and group_members.role = 'owner'
        )
    );

create policy "グループ管理者のみ予算の更新が可能" on public.group_budgets
    for update
    using (
        exists (
            select 1 from public.group_members
            where group_members.group_id = group_budgets.group_id
            and group_members.user_id = auth.uid()
            and group_members.role = 'owner'
        )
    );

create policy "グループ管理者のみ予算の削除が可能" on public.group_budgets
    for delete
    using (
        exists (
            select 1 from public.group_members
            where group_members.group_id = group_budgets.group_id
            and group_members.user_id = auth.uid()
            and group_members.role = 'owner'
        )
    );

-- インデックスの作成
create index group_budgets_group_id_idx on public.group_budgets(group_id);
create index group_budgets_category_idx on public.group_budgets(category); 